version: "3.9"

services:
  web:
    image: goweb
    restart: always
    ports:
      - "80:80"
    networks:
      - ntwords
    
  words:
    image: jwords
    restart: always
    networks:
      - ntwords

  db:
    image: dbwords
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - ntwords

  # adminer:
  #     image: adminer
  #     restart: always
  #     ports:
  #       - 8082:8080
  #     networks:
  #       - ntwords
  
networks:
  ntwords: